name: "RHCS Action"
description: "Validates the manifest.json files for RotorHazard plugins"
branding:
  icon: terminal
  color: gray-dark
runs:
  using: "docker"
  image: "ghcr.io/dutchdronesquad/rhfest-action:latest"
